import { textDerNorm } from "./text.mjs";
const API="https://models.github.ai/inference/chat/completions";

const system=`Du analysierst deutsches Steuerrecht als strukturierter Informationsextraktor. Du erteilst keine Rechtsberatung.
Gib ausschließlich valides JSON zurück. Jede Phrase in tb, rf und ausnahmen muss eine wörtliche, zusammenhängende Teilzeichenkette aus dem gelieferten Normtext sein. Tatbestand sind Voraussetzungen, Adressaten, Gegenstände, Handlungen, Zeit-/Ortselemente und negative Voraussetzungen. Rechtsfolge sind Rechtswirkungen, Pflichten, Verbote, Erlaubnisse, Ansprüche, Fiktionen, Definitionsergebnisse, Berechnungs- und Verfahrensfolgen. Erfasse mehrere Regeln, liefere aber deduplizierte Span-Listen. Klassifiziere jede Norm als rule, definition, fiction, obligation, prohibition, permission, entitlement, calculation, procedure, competence, reference_only oder no_classic_rule. Quellen dienen nur zur Plausibilisierung; sie dürfen nicht als Gesetzestextspanne ausgegeben werden. Nenne in quellen_support mindestens vier IDs. Bei Unklarheit senke konfidenz, liefere aber die wahrscheinlichste textnahe Struktur. Keine Markdown-Codeblöcke.`;

function nutzer(gesetz,batch,quellen){return JSON.stringify({gesetz:{abk:gesetz.abk,titel:gesetz.titel},referenzen:quellen.filter(q=>q.erreichbar).map(q=>({id:q.id,typ:q.typ,herausgeber:q.herausgeber,titel:q.titel,url:q.url,ausschnitt:q.ausschnitt.slice(0,3500)})),normen:batch.map(({norm,logik})=>({id:norm.id,enbez:norm.enbez,titel:norm.titel,text:textDerNorm(norm),logik_vorschlag:logik})),ausgabe_schema:{normen:[{id:"string",klassifikation:"string",tb:["wörtliche Textspanne"],rf:["wörtliche Textspanne"],ausnahmen:["wörtliche Textspanne"],konfidenz:"0..1",quellen_support:["mindestens vier IDs"],begruendung_kurz:"max. 240 Zeichen"}]}});}

export async function modellAufruf({gesetz,batch,quellen,token,modell}){const body={model:modell,messages:[{role:"system",content:system},{role:"user",content:nutzer(gesetz,batch,quellen)}],temperature:.1,max_tokens:14000,response_format:{type:"json_object"}};for(let v=1;v<=5;v++){const r=await fetch(API,{method:"POST",headers:{Accept:"application/vnd.github+json",Authorization:`Bearer ${token}`,"Content-Type":"application/json","X-GitHub-Api-Version":"2026-03-10"},body:JSON.stringify(body)});if(r.ok){const j=await r.json(),c=j.choices?.[0]?.message?.content;if(!c)throw new Error("Modellantwort ohne Inhalt");return JSON.parse(c.replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"").trim());}const f=await r.text();if(r.status===400&&body.response_format){delete body.response_format;continue;}if((r.status===429||r.status>=500)&&v<5){const p=Math.min(60000,2000*2**(v-1));console.warn(`Modell ${r.status}; neuer Versuch in ${p/1000}s`);await new Promise(x=>setTimeout(x,p));continue;}throw new Error(`GitHub Models ${r.status}: ${f.slice(0,500)}`);}throw new Error("GitHub Models nicht erreichbar");}
