import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { dekodiere, eindeutig } from "./text.mjs";

function stripHtml(h){return dekodiere(h.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim();}
async function laden(url,versuch=1){const c=new AbortController(),timer=setTimeout(()=>c.abort(),20000);try{const r=await fetch(url,{signal:c.signal,redirect:"follow",headers:{"User-Agent":"steuernorm-ki-annotation/2.0 (+https://github.com/Ccan-devoloper/steuernorm)",Accept:"text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.5"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text();}catch(e){if(versuch<3){await new Promise(r=>setTimeout(r,800*versuch));return laden(url,versuch+1);}throw e;}finally{clearTimeout(timer);}}
function token(s){return (s.toLowerCase().match(/[a-zäöüß]{4,}/g)||[]).slice(0,8);}
function ausschnitt(text,abk,titel){const s=text.replace(/\s+/g," "),teile=[];for(const w of [abk,...token(titel)]){let start=0;for(let i=0;i<3;i++){const p=s.toLowerCase().indexOf(String(w).toLowerCase(),start);if(p<0)break;teile.push(s.slice(Math.max(0,p-500),Math.min(s.length,p+1100)));start=p+String(w).length;}}if(!teile.length)teile.push(s.slice(0,2500));return eindeutig(teile).join("\n…\n").slice(0,7000);}

export async function ladeQuellen(config,gesetz,wurzel){const cache=path.join(wurzel,".cache","quellen");await mkdir(cache,{recursive:true});const fach=config.gesetze[gesetz.abk];if(!fach)throw new Error(`Keine Quellenkonfiguration für ${gesetz.abk}`);const offiziell={id:"amtlicher-text",typ:"gesetz",herausgeber:"Bundesministerium der Justiz / Bundesamt für Justiz; Spiegel: QuantLaw",titel:`${gesetz.titel} – amtlicher Normtext`,url:`https://www.gesetze-im-internet.de/${fach.slug}/`,erreichbar:true,gewicht:1,ausschnitt:`${gesetz.abk}: ${gesetz.titel}. Der vollständige gespeicherte Normtext ist die primäre Referenz.`};const liste=[...config.gemeinsame_quellen,fach.fachquelle].filter(Boolean).filter((q,i,a)=>a.findIndex(x=>x.url===q.url&&x.id===q.id)===i);const out=[offiziell];for(const q of liste){try{const seite=stripHtml(await laden(q.url));if(seite.length<80)throw new Error("kein auswertbarer Text");out.push({...q,erreichbar:true,ausschnitt:ausschnitt(seite,gesetz.abk,gesetz.titel)});}catch(e){console.warn(`Quelle nicht erreichbar ${gesetz.abk}/${q.id}: ${e.message}`);out.push({...q,erreichbar:false,fehler:e.message,ausschnitt:""});}}await writeFile(path.join(cache,`${gesetz.abk.toLowerCase()}.json`),JSON.stringify({geladen:new Date().toISOString(),quellen:out},null,2));return out;}
