import { createHash } from "node:crypto";

const ENT = new Map([["amp","&"],["lt","<"],["gt",">"],["quot",'"'],["apos","'"],["nbsp"," "],["sect","§"],["auml","ä"],["ouml","ö"],["uuml","ü"],["Auml","Ä"],["Ouml","Ö"],["Uuml","Ü"],["szlig","ß"]]);
export const TB_SIGNAL = /\b(wenn|soweit|sofern|falls|wer|wem|wessen|welche[rns]?|bei Vorliegen|unter der Voraussetzung|vorausgesetzt|nachdem|solange|bevor|durch|auf Antrag|im Fall(?:e)?|für den Fall)\b/i;
export const AUSNAHME_SIGNAL = /\b(es sei denn|ausgenommen|außer|vorbehaltlich|abweichend von|dies gilt nicht|nicht anzuwenden|entfällt|unbeschadet)\b/i;
export const RF_SIGNAL = /\b(ist|sind|gilt|gelten|hat|haben|muss|müssen|darf|dürfen|kann|können|wird|werden|unterliegt|unterliegen|beträgt|entsteht|entstehen|erlischt|erlöschen|erhöht|vermindert|festzusetzen|festgesetzt|abzuziehen|hinzuzurechnen|zu gewähren|zu versagen|verpflichtet|berechtigt|steuerfrei|steuerpflichtig|zulässig|unzulässig)\b/i;
const REINER_VERWEIS = /^(§+|Artikel|Art\.)\s*\d|nach Maßgabe|entsprechend anzuwenden|bleibt unberührt/i;

export function dekodiere(s="") { return s.replace(/&(#x?[0-9a-fA-F]+|[A-Za-z][A-Za-z0-9]*);/g,(m,e)=>{ if(e.startsWith("#x")||e.startsWith("#X")) return String.fromCodePoint(parseInt(e.slice(2),16)); if(e.startsWith("#")) return String.fromCodePoint(parseInt(e.slice(1),10)); return ENT.get(e)??m; }); }
export function textAusHtml(h="") { return dekodiere(h.replace(/<br\s*\/?\s*>/gi," ").replace(/<\/p>|<\/li>|<\/dd>|<\/dt>|<\/tr>|<\/h\d>/gi,". ").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").replace(/\s+([,.;:!?])/g,"$1").trim(); }
export function textDerNorm(n) { return n.abs.map(a=>textAusHtml(a.html)).filter(Boolean).join(" ").replace(/\s+/g," ").trim(); }
export function hashText(s) { return createHash("sha256").update(s).digest("hex"); }
export function eindeutig(a) { const g=new Set(); return a.filter(x=>{const k=typeof x==="string"?x:JSON.stringify(x); if(!k||g.has(k)) return false; g.add(k); return true;}); }
export function sauberePhrase(s,volltext) { if(typeof s!=="string") return null; const p=s.replace(/^\s*[„“\"']|[„“\"']\s*$/g,"").replace(/\s+/g," ").trim(); return p.length>=3&&p.length<=700&&volltext.includes(p)?p:null; }
export function satzSegmente(volltext) { const seg=new Intl.Segmenter("de",{granularity:"sentence"}); return [...seg.segment(volltext)].map(x=>x.segment.trim()).filter(x=>x.length>2); }

function trenne(satz) { const r={tb:[],rf:[],ausnahmen:[]}; if(AUSNAHME_SIGNAL.test(satz)) r.ausnahmen.push(satz); const k=satz.indexOf(","); if(k>3){const l=satz.slice(0,k).trim(), rr=satz.slice(k+1).trim(); if(TB_SIGNAL.test(l)&&RF_SIGNAL.test(rr)){r.tb.push(l);r.rf.push(rr);return r;}} const m=RF_SIGNAL.exec(satz); if(m&&m.index>1){const l=satz.slice(0,m.index).trim().replace(/[,:;]$/,""); const rr=satz.slice(m.index).trim(); if(l.length>=3&&rr.length>=3){r.tb.push(l);r.rf.push(rr);return r;}} if(TB_SIGNAL.test(satz)) r.tb.push(satz); else if(RF_SIGNAL.test(satz)) r.rf.push(satz); return r; }

export function logikAnalyse(norm) { const v=textDerNorm(norm),tb=[],rf=[],ausnahmen=[]; for(const s of satzSegmente(v)){const r=trenne(s);tb.push(...r.tb);rf.push(...r.rf);ausnahmen.push(...r.ausnahmen);} let k="no_classic_rule"; if(tb.length&&rf.length)k="rule"; else if(/\b(ist|sind|gilt|gelten)\b/.test(v)&&/\b(Begriff|im Sinne|bezeichnet|Definition)\b/i.test(`${norm.titel} ${v}`))k="definition"; else if(/\b(gilt als|gelten als|wird behandelt als)\b/i.test(v))k="fiction"; else if(/\b(muss|müssen|ist verpflichtet|sind verpflichtet|hat zu|haben zu)\b/i.test(v))k="obligation"; else if(/\b(darf nicht|dürfen nicht|ist unzulässig|sind unzulässig)\b/i.test(v))k="prohibition"; else if(/\b(darf|dürfen|kann|können|ist berechtigt|sind berechtigt)\b/i.test(v))k="permission"; else if(/\b(beträgt|berechnet|Bemessungsgrundlage|Steuersatz|Prozent|Euro)\b/i.test(`${norm.titel} ${v}`))k="calculation"; else if(/\b(Zuständigkeit|zuständig|Verfahren|Antrag|Frist|Klage|Einspruch)\b/i.test(`${norm.titel} ${v}`))k="procedure"; else if(REINER_VERWEIS.test(v))k="reference_only"; return {klassifikation:k,tb:eindeutig(tb).slice(0,20),rf:eindeutig(rf).slice(0,20),ausnahmen:eindeutig(ausnahmen).slice(0,12),staerke:tb.length&&rf.length?.72:(tb.length||rf.length?.45:.2)}; }

function tokens(s){return new Set((s.toLowerCase().match(/[a-zäöüß]{4,}/g)||[]).filter(x=>!["diese","dieser","dieses","einer","eines","einem","einen","sowie","werden","wurde","sind","oder","nach","durch","wenn","soweit","nicht","auch","kann","haben"].includes(x)));}
export function passtZuLogik(p,kandidaten){return kandidaten.some(k=>{if(k.includes(p)||p.includes(k))return true;const A=tokens(p),B=tokens(k);if(!A.size||!B.size)return false;let n=0;for(const x of A)if(B.has(x))n++;return n/(A.size+B.size-n)>=.48;});}
